const ROUTES = {
  START: 'Start',
  STARTNAV: 'StartNAV',
  LOGIN: 'Login',
  WRITEPROFFILE: 'WriteProfile',
  HOME: 'Home',
  BOTTOM: 'Bot',
  SEARCH: 'Search',
  SIGNIN: 'Signin',
  CHATLIST: 'ChatList',
  CHAT: 'Chat',
  LIKE: 'Like',
  PROFILE: 'Profile',
  PROFILE_EDIT: 'EditProfile',
  PROFILE_PREVIEW: 'ProfilePreview',
  SETTINGS: 'Settings',
  DETAIL: 'Detail',
  ALARM: 'Alarm',
} as const;
export default ROUTES;
